// UT Austin majors offered in the major search fields.
//
// Extracted from app/(onboarding)/CreateAccount.tsx so onboarding and Edit
// Profile share one list — they were about to drift, and a major that exists
// in one place but not the other means a user can't re-select what they
// originally picked.

export const MAJORS = [
  'Accounting',
  'Acting',
  'Actuarial Science',
  'Advertising',
  'Aerospace Engineering',
  'African and African Diaspora Studies',
  'All-Level Special Education',
  'American Studies',
  'Anthropology',
  'Applied Movement Science',
  'Architectural Engineering',
  'Architectural Studies',
  'Architecture',
  'Architecture / Architectural Engineering Dual Degree Program',
  'Art Education (UTeach Art)',
  'Art History',
  'Arts and Entertainment Technologies',
  'Asian American Studies',
  'Asian Cultures and Languages',
  'Asian Studies',
  'Astronomy',
  'Athletic Training',
  'Behavioral and Social Data Sciences',
  'Biochemistry',
  'Biology',
  'Biomedical Engineering',
  'Business Analytics',
  'Chemical Engineering',
  'Chemistry',
  'Civics Honors',
  'Civil Engineering',
  'Classical Languages',
  'Classical Studies',
  'Climate System Science',
  'Communication and Leadership',
  'Communication Studies',
  'Computational Engineering',
  'Computer Science',
  'Dance',
  'Design',
  'Early Childhood to 6th Grade Bilingual Generalist Certification',
  'Early Childhood to 6th Grade ESL Generalist Certification',
  'Economics',
  'Electrical and Computer Engineering',
  'English',
  'Environmental Engineering',
  'Environmental Science',
  'European Studies',
  'Exercise Science',
  'Finance',
  'French',
  'Geography',
  'Geological Sciences',
  'Geosystems Engineering',
  'German',
  'Government',
  'Health & Society',
  'Health Promotion and Behavioral Science',
  'History',
  'Human Development and Family Sciences',
  'Human Dimensions of Organizations',
  'Human Ecology',
  'Humanities',
  'Informatics',
  'Interior Design',
  'International Business',
  'International Relations and Global Studies',
  'Italian',
  'Jewish Studies',
  'Journalism',
  'Latin American Studies',
  'Linguistics',
  'Management',
  'Management Information Systems',
  'Marketing',
  'Mathematics',
  'Mechanical Engineering',
  'Medical Laboratory Science',
  'Mexican American & Latina/o Studies',
  'Middle Eastern Studies',
  'Music',
  'Neuroscience',
  'Nursing',
  'Nutrition',
  'Petroleum Engineering',
  'Philosophy',
  'Physical Culture and Sports',
  'Physics',
  'Psychology',
  'Public Affairs',
  'Public Health',
  'Public Relations',
  'Race, Indigeneity, and Migration',
  'Radio-Television-Film',
  'Religious Studies',
  'Rhetoric and Writing',
  'Russian, East European and Eurasian Studies',
  'Social Work',
  'Sociology',
  'Spanish',
  'Speech, Language, and Hearing Sciences',
  'Sport Management',
  'Statistics and Data Science',
  'Studio Art',
  'Supply Chain Management',
  'Sustainability Studies',
  'Textiles and Apparel',
  'Theatre and Dance',
  'Urban Studies',
  'UTeach Dance (Dance Education)',
  'UTeach Music (Music Studies)',
  'UTeach Theatre (Theatre Studies)',
  "Women's and Gender Studies",
  'Youth and Community Studies',
];
